### ISSUE TITLE
blacklist mirror not working?

### ISSUE THREAD

**Issue by koinsj** [krlvm/PowerTunnel#100]
Hello, I don't know if it's a dumb question, but I just can't figure it out.

I did a simple test to check how the domains filter works. Twitch is blocked in my country, but it's accessible with PowerTunnel running in global mode.

So I decided to fill in the blacklist mirror with the whitelist url, which does not contain Twitch's domains, and leave the local blacklist file empty, then I started the server.

09:41:16.719 [Thread-4] INFO  i.g.k.p.p.l.LibertyTunnel - Loading blacklist from mirror...
09:41:19.580 [Thread-4] INFO  i.g.k.p.p.l.LibertyTunnel - Loading local blacklist...
09:41:19.591 [Thread-4] INFO  i.g.k.p.p.l.LibertyTunnel - Loaded 72673 blocked websites

But strangely, I was still able to access Twitch.

Next I leaved the blacklist mirror empty, and copied all the domains on the whitelist url to the local blacklist file, then I started the server.

09:45:37.702 [Thread-10] INFO  i.g.k.p.p.l.LibertyTunnel - Loading local blacklist...
09:45:37.726 [Thread-10] INFO  i.g.k.p.p.l.LibertyTunnel - Loaded 72672 blocked websites

This time it seemed the filter was working and I couldn't access Twitch.

So, am I wrong or is there something wrong with the blacklist mirror?
I would really appreciate it if you could answer my question!

**Comment by krlvm** [comment]
1) The blacklist you are loading from the mirror contains only one domain (72673-72672=1)
2) Do I understand correctly that you are saying that the blacklist does not contain the Twitch domain? On the contrary, it should contain it.

**Comment by koinsj** [comment]
I will try my best to explain the problem.

I used curl to check if I could access Twitch.
I also uploaded a txt file which only contained one domain: just-test.com
https://cdn.jsdelivr.net/gh/koinsj/test@main/test.txt

Step 1, I ran curl command, but didn't start the server.
![屏幕截图(39)](https://user-images.githubusercontent.com/104575691/166494186-e557dc2e-3157-4464-b60f-1e6d58614caa.png)
Connection failed, that's not strange because Twitch is blocked in my country.

Step 2, I filled in the blacklist file with this domain: just-test.com, then started the server and ran curl command.
![屏幕截图(40)](https://user-images.githubusercontent.com/104575691/166494380-d682f0b4-4be8-402e-9a34-65d44a7ad7d1.png)
Note that I didn't put any url in the blacklist mirror.
Connection failed too, because I didn't add Twitch's domain to the blacklist. No problems so far.

Step 3, I filled in the blacklist mirror with the url I mentioned before, which only contained one domain: just-test.com. Then I started the server and ran curl command.
![屏幕截图(41)](https://user-images.githubusercontent.com/104575691/166494676-bf19acba-8a8f-4134-a1bc-5fb1e4f16391.png)
Note that the blacklist.txt was empty.
That's the problem I met. I wouldn't be able to access Twitch because from step 1 to step 3 I never added Twitch's domain to the blacklist. But in step 3, I miraculously got connected to Twitch.

So I think that either I misunderstood something or there is something wrong with the filter.

**Comment by krlvm** [comment]
Thanks for clarifying.

I think [LibertyTunnel](https://github.com/krlvm/LibertyTunnel/blob/e618924a75250a20725139785915a6f5423fdcf6/src/main/java/io/github/krlvm/powertunnel/plugins/libertytunnel/LibertyTunnel.java#L44) has enabled [global mode](https://github.com/krlvm/LibertyTunnel/blob/e618924a75250a20725139785915a6f5423fdcf6/src/main/java/io/github/krlvm/powertunnel/plugins/libertytunnel/ProxyListener.java#L75), but I'm not sure why. It automatically enables if the blacklist is empty, maybe it failed to load it from the mirror and the local blacklist also was empty, can you check please?

**Comment by koinsj** [comment]
I don't know if it really loaded the mirror, but at least it told me so.
![屏幕截图(43)](https://user-images.githubusercontent.com/104575691/166639086-adbaf3d3-c856-4bdb-ae88-da898fc2ac09.png)

And the result was same as before.
![屏幕截图(44)](https://user-images.githubusercontent.com/104575691/166639291-b512cf91-d33e-422e-98f5-8c30f05608cd.png)

PS: I don't really understand why there were two being loaded, but it seemed that it would load one even I didn't add anything.
![屏幕截图(46)](https://user-images.githubusercontent.com/104575691/166639764-d2d001f8-ac5b-475d-be92-52572b52bd7c.png)

**Comment by krlvm** [comment]
Try this build of LibertyTunnel to figure out what happens actually

[LibertyTunnel.zip](https://github.com/krlvm/PowerTunnel/files/8619875/LibertyTunnel.zip)

**Comment by krlvm** [comment]
Oh, so it's simple: you have an empty string somewhere, and obviously any domain is considered its subdomain.

**Comment by krlvm** [comment]
Well, it's my fault :/
LibertyTunnel did not remove the empty line at the EOF while loading a blacklist

**Comment by krlvm** [comment]
Thanks for discovering this, fixed with [LibertyTunnel v1.0.4](https://github.com/krlvm/LibertyTunnel/releases/tag/v1.0.4).
I will release new PowerTunnel Desktop & Android versions with updated plugin soon.

**Comment by koinsj** [comment]
So this is the "1 blocked websites" that came from nowhere. In the end it was just a tiny problem.🤣
Other than this little problem, PowerTunnel is really great. Thanks for your hard work!
