### ISSUE TITLE
Microsoft Store and Xbox application inaccessible when PowerTunnel is turned on

### ISSUE THREAD

**Issue by Oddity-Official** [krlvm/PowerTunnel#102]
If you turn off the proxy server, they work fine. Is there a way to filter Microsoft services?

Using PowerTunnel v2.3 and Windows 10. 

EDIT: From the Wiki: "If you're using Windows 10 it's highly recommended to add all Microsoft servers to the exception list to boost performance." so it seems it's possible to filter out Microsoft servers, but it doesn't say how.

**Comment by krlvm** [comment]
Sorry, forget to document this.
Put `*.microsoft.com` into this box.
You may also need to add Xbox domains, e.g. `*.microsoft.com;*.xbox.com`

![image](https://user-images.githubusercontent.com/51774833/172229296-366dcc54-28e0-4f74-a1fd-65ae11cdab22.png)

**Comment by Oddity-Official** [comment]
Thanks for the reply!

I did as you said, but it doesn't seem to be working. Or, more accurately, it seems to be working weirdly.

Microsoft Store now loads, but it takes a long time for it to do so. When it does load, the banners don't seem to work and some of the thumbnails are missing.

![image](https://user-images.githubusercontent.com/72626901/172235600-f2ac3787-2283-42b2-845d-25f98b3183e9.png)

And as for the Xbox app, it doesn't seem to load at all.

![image](https://user-images.githubusercontent.com/72626901/172235729-33dafb5f-d56d-4184-97aa-632e2752b6d3.png)

Here's what my proxy settings look like:

![image](https://user-images.githubusercontent.com/72626901/172236085-ce41bd8f-11c6-4909-9bd4-95a4ea2b82e1.png)

**Comment by krlvm** [comment]
Indeed, it does not even send a connection request - I don't remember it was behaving like that before, should've changed with recent Windows updates.

**Comment by krlvm** [comment]
UPD: it worked right after I disabled LibertyTunnel plugin. Looks like they don't like fragmented packets.
Try filling `government-blacklist.txt` configuration file to disable anti-DPI tricks for non-blocked websites.

**Comment by krlvm** [comment]
UPD2: putting this into proxy settings helped me:
`*.microsoft.com;*.msn.com;*.windows.com;*.bing.com`

**Comment by Oddity-Official** [comment]
> UPD: it worked right after I disabled LibertyTunnel plugin. Looks like they don't like fragmented packets. Try filling `government-blacklist.txt` configuration file to disable anti-DPI tricks for non-blocked websites.

I put in one blocked website ("okcupid.com") into the `"government-blacklist.txt"` that was in `"/PowerTunnel/configs/"`. 

`".okcupid.com"` worked. And allowed access to the website.

`"*.okcupid.com"` didn't work. Not quite sure why. Might be another potential issue.

Tried a different blocked website ("xhamster.com"). I tried both `".xhamster.com"` and `"*.xhamster.com"`, neither of them worked. It worked fine before I put anything into the blacklist.

This is the error I get on Firefox when I try to access a blocked website with PowerTunnel on and said website in the blacklist.

![image](https://user-images.githubusercontent.com/72626901/172256047-a5e6fde0-1822-4fce-ab96-8b22a7e9597f.png)

I might be doing something wrong here though. I was following [this section of the Wiki](https://github.com/krlvm/PowerTunnel/wiki/Installation#configuring-dpi-circumvention).

Anyway, with just ".okcupid.com" in the blacklist file, I tried to see if the Microsoft store or the Xbox app worked, but it didn't. It was still just like before.

> UPD2: putting this into proxy settings helped me: `*.microsoft.com;*.msn.com;*.windows.com;*.bing.com`

I put all of that in but it only seemed to have slightly improved it.

![image](https://user-images.githubusercontent.com/72626901/172260835-29d8c255-534e-47a3-99a2-91628d742461.png)

Now I can see some more of the thumbnails and screenshots, but some of them are still missing. I'm also getting an error saying that I don't have an internet connection now.

![image](https://user-images.githubusercontent.com/72626901/172260936-1e4882d9-defc-4019-8036-238bf46d28e9.png)

On the Xbox app though, it's still not working at all. Sometimes it loads a thumbnail or two, but it doesn't load anything else.

I also tried doing both these fixes at the same time (".okcupid.com" in the blacklist and the new proxy settings), still didn't work sadly.

**Comment by krlvm** [comment]
Sorry, I apparently forgot to update that part of the documentation (again).
Now you don't have to write `*.`, i.e. if you need to access `sub1.example.com`, just write `example.com`. I've updated that part.

**Comment by krlvm** [comment]
> I also tried doing both these fixes at the same time (".okcupid.com" in the blacklist and the new proxy settings), still didn't work sadly.

Will you able to access the Microsoft Store if you disable LibertyTunnel completely?

**Comment by Oddity-Official** [comment]
No. I still can't access it.

**Comment by krlvm** [comment]
Should be related to base proxy implementation, I'll look into it.

If you want to reduce the CPU usage and improve performance, you can configure proxy server exclusively in your browser (available in Firefox settings or via ProxySwitchyOmega extension for Chrome) and disable system-wide proxy, or generate Proxy Automatic Configuration file (PAC) via LibertyTunnel to make Windows proxying only blocked sites - fill the blacklist, enable corresponding option in LibertyTunnel and specify path to PAC file with `file:///` prefix.

**Comment by Oddity-Official** [comment]
Woo! Configuring the proxy server in Firefox worked for me. I can access blocked websites _and_ Microsoft services now.

Thank you for your help!

**Comment by DRSDavidSoft** [comment]
I think this is a case of AppContainer loopback blocks in Windows, as the UWP/Store apps cannot connect to a local instance of proxy server.

Solution is to use the Telerik's **[EnableLoopBackUtility]**(https://telerik-fiddler.s3.amazonaws.com/fiddler/addons/enableloopbackutility.exe) in order to exempt the store apps from this limitation.

I'm pretty sure the installed root CA is usable by store apps BTW
