### ISSUE TITLE
Что делают с UI ключи disable-native-lf и disable-ui-scaling ?

### ISSUE THREAD

**Issue by Baltazar500** [krlvm/PowerTunnel#11]
Что делают ключи disable-native-lf и disable-ui-scaling ?

Первый вроде как должен отключать перевод строки (хотя я таки не понял где), а второй масштабирование. Вот только изменений в исходнике страницы UI (сливал через curl в файл), что с  disable-native-lf и disable-ui-scaling, что без них не обнаружил. В браузере соотвественно изменений тоже не обнаружил.

p.s.

Пока разбирался с UI, в один из перезапусков, переключаясь с ключей -disable-ui-scaling и -disable-updater словил в UI при их отключении 

>"Bad Gateway: http://powertunnelmonitorabc111.info/" 

и так повторялось несколько раз перезапуская. 

Когда включил с disable-ui-scaling (кажется это был он, хотя это мог быть и  disable-native-lf), всё заработало нормально, а потом после очередного рестарта PowerTunnel'я его UI стало работать номально без этого ключа.

Это наверное надо было в отдельное issue выделить ?

**Comment by krlvm** [comment]
Эти ключи отвечают за внешний вид интерфейса программы, и немного за контекстное меню в трее.

- `-disable-native-lf` - отключает установку системного Java Swing Look&Feel, вместо этого используется стандартный. Системный Look&Feel есть у Windows, у рабочего окружения GNOME и macOS. Возможно, этот список чуть больше
  - Стандартный L&F:
![java-lf-standard](https://user-images.githubusercontent.com/51774833/81742756-45397a00-94a9-11ea-867e-af2772cace29.png)
  - Windows L&F:
![java-lf-win](https://user-images.githubusercontent.com/51774833/81742966-92b5e700-94a9-11ea-8ca0-70b994cfec04.png)
 - GNOME L&F (старый скриншот, баги в интерфейсе с этим L&F уже исправлены):
![java-lf-gnome](https://user-images.githubusercontent.com/51774833/81743036-ae20f200-94a9-11ea-9216-52c3a0b8221a.png)

- `-disable-ui-scaling` - отключает масштабирование DPI Scaling (Dots Per Inch, точки на дюйм), которое включается при установке масштабирования интерфейса ОС > 100%, обычно на FullHD дисплеях и выше. Чуть подробнее в [репозитории библиотеки SwingDPI](https://github.com/krlvm/SwingDPI). Поиграться со значениями можно используя ключ `-set-scale-factor [n]`, где `n` - число или десятичная дробь от 1.0 до бесконечности. У меня установлено масштабирование 125%, слева - без масштабирования, справа - с масштабированием:
![powertunnel-dpi-scaling](https://user-images.githubusercontent.com/51774833/81743451-51720700-94aa-11ea-8ba4-4cefb02658c6.png)

**Comment by krlvm** [comment]
На Ubuntu 18.04 LTS это выглядит так:
![java-gnome-lf-stable](https://user-images.githubusercontent.com/51774833/81744836-69e32100-94ac-11ea-8a21-f8074fb82719.png)

Но работает это нормально только с JRE8, при использовании OpenJDK JRE11 на последней Ubuntu 20.04 LTS происходит что-то непонятное, для таких случаев и предусмотрена возможность отключить системный L&F:
![java-gnome-lf-bug](https://user-images.githubusercontent.com/51774833/81744533-03f69980-94ac-11ea-8b67-5590e0383404.png)

**Comment by Baltazar500** [comment]
>Эти ключи отвечают за внешний вид интерфейса программы, и немного за контекстное меню в трее.

А, понятно, это имелось ввиду обычный UI. Я из-за такого набора ключей

>-with-web-ui [appendix] - enables Web UI at http://powertunnelmonitor[appendix].info

>***

>-disable-native-lf - disables native L&F (when UI enabled)
>-disable-ui-scaling - disables UI scaling (when UI enabled)

в голове получилась каша и я подумал, что речь про web UI и упорно искал там изменения (программа запускалась в консольном режиме) :)

В общем вопрос закрыт, спасибо за объяснения :) Если "Bad Gateway" будет снова лезть в web ui, открою отдельное issue.
