### ISSUE TITLE
CLI  --upstream-auth-password not found

### ISSUE THREAD

**Issue by nakcont** [krlvm/PowerTunnel#113]

**Comment by krlvm** [comment]
Good catch

**Comment by nakcont** [comment]
> Good catch

Hi krlvm, you can add upstream_proxy_protocol in cli ? I think it's also important
Thanks.

**Comment by krlvm** [comment]
Released the fix with [v2.4.1](https://github.com/krlvm/PowerTunnel/releases/tag/v2.4.1)

**Comment by nakcont** [comment]
> Released the fix with [v2.4.1](https://github.com/krlvm/PowerTunnel/releases/tag/v2.4.1)
Wow, so fast.
but version v2.4.1 not found cli --upstream-proxy-protocol. It will be great if you update it

**Comment by krlvm** [comment]
I had the plans to implement it, released in [v2.5](https://github.com/krlvm/PowerTunnel/releases/tag/v2.5) along with other fixes.

**Comment by nakcont** [comment]
> I had the plans to implement it, released in [v2.5](https://github.com/krlvm/PowerTunnel/releases/tag/v2.5) along with other fixes.

You are great, thanks you very much.
