### ISSUE TITLE
Powertunnel not working on mobile data

### ISSUE THREAD

**Issue by talu1999** [krlvm/PowerTunnel#116]
it is working fine when connected via wifi but it doesn't work on mobile data for some reason... please help..

**Comment by krlvm** [comment]
Your mobile provider has a different filtration system.
Enabling SNI Modification and disabling all other options may help you.

**Comment by talu1999** [comment]
> Your mobile provider has a different filtration system. Enabling SNI Modification and disabling all other options may help you.

How to do that?? @krlvm

**Comment by krlvm** [comment]
The option is on the bottom of the LibertyTunnel plugin settings. Please remember you should disable all other LibertyTunnel options. Recommended SNI Modification mode is Fake SNI. It may break compatibility with some websites, so it is recommended to fill the list of the sites which are currently blocked, so this would not be applied to already-working websites. You can do this by long-pressing gear icon of LibertyTunnel plugin and editing `government-blacklist.txt`. One domain is one line.
