### ISSUE TITLE
Random sites give closed connection

### ISSUE THREAD

**Issue by N1N74** [krlvm/PowerTunnel#120]
Sites: (ones I recall)
https://www.epicgames.com/
https://www.manchester.ac.uk/ (http loads)

Same issue on android as well as windows. Tested across different networks and dns settings. It does work in unblocking blocked sites, few unblocked sites such as these become inaccessible as powertunnel is turned on.

**Comment by krlvm** [comment]
Fill `government-blacklist.txt` with banned sites (hold gear icon on LibertyTunnel plugin to access it on Android) to apply tricks selectively

**Comment by N1N74** [comment]
Oh, that's great. Can confirm that its working.
