### ISSUE TITLE
Fake SNI broke website

### ISSUE THREAD

**Issue by willsionggg** [krlvm/PowerTunnel#134]
Hi can you make fake SNI stable I can't use some website like reddit and so on and  also can't watch live streams on twitch  but youtube is working and yet I can't download videos it said something about certificate . the reason why I want to use this is not because of blocking website no I use it to get all of internet speed cause  my ISP throttling my internet Except for one website which  I use it as an  SNI  and yes this trick is working  when I use v2rayN or OPENVPN with Stunnel also working fine with just SSH  and SNI  like this script: https://github.com/abdoxfox/http-ssl-ssh-injector.
ok your software is working its give me full speed but broke  website maybe if you try something like allowing insecure connection just like v2rayN have I don't know maybe .
why I want to use your software  cause I don't want to change my IP    cause all the software I TALKED About change your IP.
Thank you for reading and sorry for my English it's not my first language

**Comment by krlvm** [comment]
It is by design - that's how SNI modification & MITM works.
Unfortunately, nothing can be done without using an external proxy that will relay traffic with the real SNI and certificate.

**Comment by willsionggg** [comment]
then ill stick with v2ray anyway thank you for replaying 
Have a good day
