### ISSUE TITLE
[Suggestion] Fake Packet mode

### ISSUE THREAD

**Issue by maximmax42** [krlvm/PowerTunnel#137]
If I understand correctly, PT currently doesn't have a fake packet mode as seen in GoodbyeDPI and GhosTCP, so it would be great to see it added, especially to the Android version. Currently, PT can't fully unblock everything for me, but those 2 programs can with fake packets enabled.

**Comment by krlvm** [comment]
I would have done this a long time ago, but with Java it is impossible to interact with the network at such a low level, and on Android it would require root :(

**Comment by maximmax42** [comment]
Ah. Well, that's unfortunate. Thanks for reply.
