### ISSUE TITLE
Cant connect internet

### ISSUE THREAD

**Issue by denzbayy** [krlvm/PowerTunnel#148]
I installed powertunnel root cert. When i use fake sni i cant connect anything. I have unlimited youtube,whatsapp data on my celluar data. I use pdanet to share the net. When i use tls tunnel with youtube.com sni and random server it works. But i have ping. Can this application fix my problem? What should i type into ip and port? Im in Turkey do i have to rent proxy or smthn? What apps can i use? Im using powertunnel on my pc btw. I have no celluar data left but when i share my internet to pc i can connect youtube. If i install it on my phone will it work?

**Comment by denzbayy** [comment]
I installed it and cert on my phone it didnt work. 
![image](https://github.com/krlvm/PowerTunnel/assets/138827931/0417f719-9c82-4f76-8e98-dd8fa208ce53)
![image](https://github.com/krlvm/PowerTunnel/assets/138827931/7b620a02-f32c-47c5-babe-334919faa856)

**Comment by denzbayy** [comment]
i can connect youtube. but with these setting i cant.

**Comment by denzbayy** [comment]
i connected to a proxy but with fake sni i get this error can u help me? 
![image](https://github.com/krlvm/PowerTunnel/assets/138827931/0e464a47-be07-4e46-b95b-3c32d7d487d5)

**Comment by krlvm** [comment]
You won't get the same effect as using external proxies, SNI modification/MITM breaks compatibility with most sites.

> i connected to a proxy but with fake sni i get this error

You corrupted application configuration and/or the generated certificate, you can delete the file and it will be generated again, the old certificate can be uninstalled then.

**Comment by denzbayy** [comment]
hi i have unlimited youtube data. I wanna use it on other sites. Can this work without buying proxy? Do i have to buy proxy or something?
