### ISSUE TITLE
PR_END_OF_FILE_ERROR on only some websites

### ISSUE THREAD

**Issue by EmiliaTheGoddess** [krlvm/PowerTunnel#149]
Hello. I'm getting PR_END_OF_FILE_ERROR on some websites. For example, this happens on f95zone.
![image](https://github.com/krlvm/PowerTunnel/assets/43678100/9f33dba5-0d03-4355-9bf3-b4e65ac74238)
Strange thing is, it only happens on few select websites. I'm able to connect other blocked websites like pastebin just fine. I tried messing with the settings. Changing the chunk size or using SNI modification did not help. Is there any particular reason why this can happen?

My ISP is a Turkish service provider named "Gıbırnet". Thanks for your attention.

**Comment by krlvm** [comment]
Perhaps the site itself has problems with processing fragmented packets, I encounter the same problem with some sites, happens when using GoodbyeDPI too, so I have to connect to the VPN every time.
