### ISSUE TITLE
Не грузятся изображения на lostfilm.tv

### ISSUE THREAD

**Issue by Baltazar500** [krlvm/PowerTunnel#15]
Не хотят грузиться изображения с лостфильма. Сам сайт через PowerTunnel грузится, а пикчи - нет. http://sendpic.org/view/1/i/3v22k73aeU6YJNmTviEdLPxMvVp.jpg

Пикчи расположены на хосте static.lostfilm.tv, например  https://static.lostfilm.tv/Images/407/Posters/icon.jpg

Вот что говорит curl :

>`curl -A "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:52.0) Gecko/20100101 Firefox/52.0" -svkL -x 127.0.0.1:8085 "https://static.lostfilm.tv/Images/407/Posters/icon.jpg"`
>`*   Trying 127.0.0.1...`
>`* TCP_NODELAY set`
>`* Connected to 127.0.0.1 (127.0.0.1) port 8085 (#0)`
>`* allocate connect buffer!`
>`* Establish HTTP proxy tunnel to static.lostfilm.tv:443`
>`> CONNECT static.lostfilm.tv:443 HTTP/1.1`
>`> Host: static.lostfilm.tv:443`
>`> User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:52.0) Gecko/20100101 Firefox/52.0`
>`> Proxy-Connection: Keep-Alive`
>`>`
>`< HTTP/1.1 200 Connection established`
>`< Connection: keep-alive`
>`< Via: 1.1 HostPC`
>`<`
>`* Proxy replied 200 to CONNECT request`
>`* CONNECT phase completed!`
>`* ALPN, offering h2`
>`* ALPN, offering http/1.1`
>`} [5 bytes data]`
>`* TLSv1.2 (OUT), TLS handshake, Client hello (1):`
>`} [216 bytes data]`
>`* CONNECT phase completed!`
>`* CONNECT phase completed!`
>`{ [5 bytes data]`
>`* TLSv1.2 (IN), TLS handshake, Server hello (2):`
>`{ [104 bytes data]`
>`* TLSv1.2 (IN), TLS handshake, Certificate (11):`
>`{ [2806 bytes data]`
>`* TLSv1.2 (IN), TLS handshake, Server key exchange (12):`
>`{ [365 bytes data]`
>`* TLSv1.2 (IN), TLS handshake, Server finished (14):`
>`{ [4 bytes data]`
>`* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):`
>`} [102 bytes data]`
>`* TLSv1.2 (OUT), TLS change cipher, Client hello (1):`
>`} [1 bytes data]`
>`* TLSv1.2 (OUT), TLS handshake, Finished (20):`
>`} [16 bytes data]`
>`* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to static.lostfilm.tv:443`
>`* stopped the pause stream!`
>`* Closing connection 0`

настройки использовал базовые 

>javaw -jar PowerTunnel.jar -start -console -disable-updater

>http.mix-host-case.bool=true
>powertunnel.government-blacklist-mirror=
>server.auto-setup.bool=false
>https.chunking.size.int=2
>http.payload.length.int=0
>server.ip=127.0.0.1
>https.chunking.full.bool=true
>dns.doh.address=
>server.port.int=8085
>dns.dnssec.enabled.bool=false
>powertunnel.journal.enabled=false
>http.invalid-packets.allow=true

**Comment by krlvm** [comment]
Судя по конфигурации, вы используете устаревшую версию, попробуйте обновиться до версии 1.11, в ней были исправлены некоторые баги LittleProxy, в том числе "bad gateway", что может являться причиной проблемы:
![lstflm](https://user-images.githubusercontent.com/51774833/82116435-8912d480-9772-11ea-9c4b-cdd9e048fae0.png)

**Comment by Baltazar500** [comment]
PowerTunnel 1.11, но конфиг остался от старого билда. Удалю его и посмотрю изменится ли поведение lostfilm.tv

**Comment by Baltazar500** [comment]
Удалил settings.ini, запустил PowerTunnel с теми же параметрами из консоли, что указывал выше и проблема ушла. При запуске создался новый settings.ini, который был пуст (он остался пустым и по завершении программы по ctrl+c).

**Comment by krlvm** [comment]
> Удалил settings.ini, запустил PowerTunnel с теми же параметрами из консоли, что указывал выше и проблема ушла. При запуске создался новый settings.ini, который был пуст (он остался пустым и по завершении программы по ctrl+c).

Этот параметр отвечает за решение [проблемы](https://github.com/krlvm/PowerTunnel-Android/issues/15) с "bad request"
![alrtos](https://user-images.githubusercontent.com/51774833/82189285-cce31680-98f7-11ea-97c9-068adc479ec7.png)
