### ISSUE TITLE
Авто старт

### ISSUE THREAD

**Issue by Pepcola619** [krlvm/PowerTunnel#156]
Как на винде сделать автостарт приложения со стартом сервера?

**Comment by krlvm** [comment]
Простейший способ - закинуть батник в `shell:startup`, либо, если у вас есть права администратора и вы готовы использовать обход в глобальном режиме, использовать GoodbyeDPI

**Comment by Pepcola619** [comment]
Как я понял бантик запускает саму программу, а старт всеровно руками нужно будет нажать?

**Comment by Pepcola619** [comment]
>  либо, если у вас есть права администратора и вы готовы использовать обход в глобальном режиме, использовать GoodbyeDPI

В домашней сети хочу развернуть сервер на одном из пк, дял остальных устройств(телефоны, смарт приставки и тд)

**Comment by Pepcola619** [comment]
Или ищу способ установки на keenetic.

**Comment by krlvm** [comment]
> Или ищу способ установки на keenetic.

zapret
