### ISSUE TITLE
Feature request: apps filter

### ISSUE THREAD

**Issue by Be1zebub** [krlvm/PowerTunnel#157]
On android version there is a way to filter which apps will proxy through powertunnel - its very useful, but it seems this feature is not available in the main version (at least in windows).

**Comment by krlvm** [comment]
Per app filtering is not possible at proxy level

**Comment by Be1zebub** [comment]
maybe is there way to use power tunnel only for browser? it seems to work like a regular proxy.

**Comment by krlvm** [comment]
It is. You can configure proxy natively in Firefox or using command line launch arguments or extensions in Chrome.
