### ISSUE TITLE
Перестал работать powertunnel!!!

### ISSUE THREAD

**Issue by Enotik36514** [krlvm/PowerTunnel#162]
Огромная проблема, приехал с Молдовы в Россию а тут целый набор санкций, ну и я начал с ними как то справляться, пытался обойти их какими то костылями и т.д. и тут нашёл эту замечательную программу, но вот беда всё хорошее заканчивается и я не понимаю что произошло и какова причина тому что программа перестала работать в принципе хотя показывает что сервер запущен
![изображение](https://github.com/user-attachments/assets/886a78f1-2a0f-48b1-8ff3-282147c22467)

**Comment by krlvm** [comment]
Все способы обхода блокировок с одной стороны ограничены интернет-стандартами, с другой - системами фильтрации, которые продолжают совершенствовать. Возможно, поможет последняя версия [GoodbyeDPI](https://github.com/ValdikSS/GoodbyeDPI), но и это не надолго - у меня она уже не работает.
