### ISSUE TITLE
Не работает с 26.09

### ISSUE THREAD

**Issue by DenimTornado** [krlvm/PowerTunnel#163]
Судя по всему изменилась схема блокировок, теперь и ютуб не открывается и любые другие сайты из соответствующего списка. Есть шанс, что тоннель снова заработает?

**Comment by PoorMouse** [comment]
Я так понимаю, приложение окончательно умерло. У меня оно ни разу не работало.

**Comment by krlvm** [comment]
Это не в приложении дело, а в системах фильтрации
