### ISSUE TITLE
internet not working if i dont start the powertunnel

### ISSUE THREAD

**Issue by theoirawan** [krlvm/PowerTunnel#17]
when i dont use powertunnel, the internet isnt working

it says :
No internetThere is something wrong with the proxy server, or the address is incorrect.
Try:

Contacting the system admin
Checking the proxy address
Running Windows Network Diagnostics
ERR_PROXY_CONNECTION_FAILED

so i have to start powertunnel everytime.. can someone help me?

**Comment by krlvm** [comment]
You should disable proxy server in your OS settings after you stopped PowerTunnel.
If you're on Windows, it should be disabled automatically, if it doesn't, open Internet Explorer, it should resolve the problem.

Manual for Windows 10: https://answers.microsoft.com/en-us/windows/forum/windows_10-other_settings/how-to-disable-proxy-on-windows-10/02cf6980-2b5c-4ac9-aa25-4a61f26375e9
Manual for Windows XP and higher: https://buy.fineproxy.org/eng/articles/how-to-remove-proxy-settings-in-windows.html
