### ISSUE TITLE
powertunnel not working

### ISSUE THREAD

**Issue by theoirawan** [krlvm/PowerTunnel#19]
recently i change my antivirus from avast to Eset NOD32 internet security. now i powertunnel seems not working.,. i cant access netflix anymore. what should i do?

![image](https://user-images.githubusercontent.com/65608227/85191826-7ac45500-b2ea-11ea-901c-eaf58ad1f600.png)

**Comment by krlvm** [comment]
Check your system proxy settings.
Enable logs in settings and check their state.

![1](https://user-images.githubusercontent.com/51774833/85198621-c11db200-b2f2-11ea-9e1e-681b326232b4.png)
![2](https://user-images.githubusercontent.com/51774833/85198624-c3800c00-b2f2-11ea-8b25-764fcd4a99b3.png)

**Comment by theoirawan** [comment]
![image](https://user-images.githubusercontent.com/65608227/85205869-513a1680-b348-11ea-8b92-1a5065ded9b3.png)

![image](https://user-images.githubusercontent.com/65608227/85205874-58f9bb00-b348-11ea-94bd-2ac85d17bf75.png)


still not working

**Comment by krlvm** [comment]
Does the Android version work?

**Comment by theoirawan** [comment]
android version work on my phone.. but the pc version not working. please help

**Comment by krlvm** [comment]
I assume the problem can be related to your antivirus software, please, try to disable any kind of your AV firewall.
Manual for Eset NOD32: https://help.eset.com/eis/13/en-US/idh_config_epfw_basic_group.html

You can try to boot in safe mode with network support and check does the program work.

**Comment by theoirawan** [comment]
already uninstall my AV, and disable my firewall still no working..

![image](https://user-images.githubusercontent.com/65608227/85227436-abe67780-b407-11ea-8eb9-f30f8a927060.png)

**Comment by theoirawan** [comment]
problem solved.. i fill the DNS resolver to google DNS..

![image](https://user-images.githubusercontent.com/65608227/85227727-662aae80-b409-11ea-8726-10697b9d2c54.png)

**Comment by N1N74** [comment]
Hey, I had the same issue when I enabled Encrypted DNS in windows settings. Powertunnel stopped working with simplewall enabled. 

Enabling DNSSec option in the DNS plugin fixes this. No need to change DNS from PT.
PT v2.5.2
