### ISSUE TITLE
High RAM usage

### ISSUE THREAD

**Issue by tosunkaya** [krlvm/PowerTunnel#24]
Thanks for developing this awesome app. I have JDK14+JDK8+JRE installed. When i run Powertunnel, javaw.exe increases to 400mb (enabled), 85mb (disabled). Is there any way to reduce this or choose to use JRE instead of JDK?

**Comment by krlvm** [comment]
Hello.

We need to clarify a few things at the first, JDK (Java Development Kit) is a regular JRE (Java Runtime Environment, the virtual machine, that interprets the bytecode and runs the application) plus the stuff that is need to develop and build Java applications.\
So, this doesn't matter what you have installed - JRE or JDK.\
If you do not develop Java apps, you can uninstall JDK and install a regular JRE to save disk space.

When I use PowerTunnel on Windows, the average RAM usage is 100-150 MB. The main source of the memory consumption is the underlying proxy server (LittleProxy), that is highly optimized though.

Can you share your PowerTunnel settings (screenshot of the options window or `settings.ini`)?\
What operating system do you use (Windows/Linux/macOS)?\
Are you seeing this issue on Android?

I have a few suggestions at this point:
- You can try to launch PowerTunnel in console mode, so you can try economy the memory (and CPU usage) by disabling the User Interface: `javaw -jar PowerTunnel.jar -console;
- Remove the asterisk (`*`) from `government-blocklist.txt` and put there all hosts that is blocked in your country, you can find this list in the Internet, so the resources of your PC will be saved thanks to applying trick only to necessary sites;
- I developed another solution that should solve that problem a month ago, but haven't published it yet. The solution is to use PAC (proxy auto configuration) to use the proxy only for necessary sites, this will economy even more resources than the previous method.

Waiting for your reply.

**Comment by tosunkaya** [comment]
I runned via cmd `javaw -jar PowerTunnel.jar -console`, when it's enabled, total usage is 90mb (increases-now 98mb). which is better than 400mb.
but goodbyedpi just uses 6mb. My settings are default (not used any blacklist). OS: Windows 10 latest.
![image](https://user-images.githubusercontent.com/12996767/90336485-d1959480-dfe4-11ea-9e46-b82bcf9c58d2.png)
![image](https://user-images.githubusercontent.com/12996767/90336634-cb53e800-dfe5-11ea-89c6-7e2083e0e5d0.png)

**Comment by krlvm** [comment]
The difference is that GoodbyeDPI is injects into the Windows network stack, when PowerTunnel is a proxy server that should intercept and deconstruct and analyze the traffic. Unfortunately LittleProxy is not as optimized as we would like it to be.

I have a plan to move to a native and optimized proxy server written in C/C++, but haven't find a good replacement yet.\
The problem can be partially fixed for now by using blacklists in combination with PAC, which I will release within a few hours.

**Comment by krlvm** [comment]
The temporary fix is available in [version 1.13](https://github.com/krlvm/PowerTunnel/releases/tag/v1.13), you can use PAC in combination with government blocklist to reduce RAM usage by reducing the count of connections to the proxy

**Comment by krlvm** [comment]
I found a solution.
The actual RAM usage is actually low, the problem is that memory never returns from heap to operating system.
Launch PowerTunnel with JVM argument `-XX:+UnlockExperimentalVMOptions -XX:+UseG1GC`.
