### ISSUE TITLE
Запуск PT на нескольких интерфейсах одновременно ?

### ISSUE THREAD

**Issue by Baltazar500** [krlvm/PowerTunnel#26]
Как на десктопном PT запустить прокси одновременно на локалхосте и основном интерфейсе (ip-адресе) ? Два параметра ip исключают друг друга и PT применяет прописанный последним.

**Comment by krlvm** [comment]
Использование IP-адреса `0.0.0.0` должно сработать.

**Comment by Baltazar500** [comment]
>Использование IP-адреса 0.0.0.0 должно сработать.

Да. Это помогло :)
