### ISSUE TITLE
PowerTonnel при активации опций SNI из консоли не создаёт сертификаты в директории программы.

### ISSUE THREAD

**Issue by Baltazar500** [krlvm/PowerTunnel#27]
При запуске PowerTonnel при активации опций SNI из консоли не создаёт сертификаты в директории программы. Только после активации этих опций из GUI.

**Comment by krlvm** [comment]
Только сейчас заметил, что забыл переименовать в парсере CLI `-erase-sni` в `-sni-trick`, `-sni-fake-host` также не работает.
