### ISSUE TITLE
inserts a line break before 'GET' method (перенос перед GET) для обхода блокировки на десктопной версии PT не работает. Но работает на Android.

### ISSUE THREAD

**Issue by Baltazar500** [krlvm/PowerTunnel#28]
Недавно обнаружил, что PT на Android позволяет обходить блокировку по http с опцией "inserts a line break before 'GET' method (перенос перед GET)", решил перепроверить эту опцию на десктопе (хотя я там ранее уже всё перепробовал) и как и следовало ожидать, продолжил напарываться на заглушку провайдера (почему - хз). 

В итоге в PT на Android у меня работает обход по http, а на десктопе по https :D

**Comment by krlvm** [comment]
Скорее всего что-то перехватывает и модифицирует (корректирует) трафик в вашей ОС, поскольку реализации этого метода абсолютно идентичны.

**Comment by Baltazar500** [comment]
>Скорее всего что-то перехватывает и модифицирует (корректирует) трафик в вашей ОС, поскольку реализации этого метода абсолютно идентичны

Была такая мысль, только глубоко не копал. Попробовал для начала рубануть AdMuncher, который в саоё время доставил геммороя с http-onion-версией рутрекера, но проблема не ушла. Возможно дело в антивирусе. Попробую покопать в эту сторону. Гляну, что там в дампах шарка.

**Comment by Baltazar500** [comment]
Собственно, как я и подозревал, виновником оказался KIS (Kaspersky Internet Security). Остановка защиты сразу же даёт положительный эффект и обход по http начинает работать. Включаю - облом. Добавляю PowerTunnel.jar и в доверенные и в исключения - всё равно получаю облом. 

KIS продолжает выправлять http и обрезать 0d0a перед GET. Мда. http он прозрачно фильтрует. Что делать при таком раскладе я хз. Или там надо exe-ки явы исключать из фильтрации ? Хотя так себе конечно решение, если сработает.

**Comment by krlvm** [comment]
> Или там надо exe-ки явы исключать из фильтрации ?

Да, а именно исполняемые файлы `java` и `javaw`.

Если есть опасения по поводу безопасности (любое приложение на Java будет обходить KIS), то можно попробовать создать на них [на исполняемые файлы] символические ссылки, добавить их в исключения и запускать приложение через них (`java -jar PowerTunnel.jar ...`).

Но лучше в таком случае просто создать папку с портативным дистрибутивом Java, добавить его исполняемые файлы в исключения и запускать приложение через них, поскольку насчет символических ссылок я не уверен.

**Comment by Baltazar500** [comment]
Вариант с симлинком не прокатил. KIS работает с ним как с оригиналом. Т.е. добавив симлинк (через Link Shell Extension) я получил игнор и обычной явы антивирусом. Так только портабельный варианет явы в довесок

**Comment by Baltazar500** [comment]
На XP вариант с портабельной явой (8.231) и исключениями не прокатил. Антивирус даже при наличии исключений вмешивается в http - траффик. Причём версия антивируса та же. Только KAV, а не KIS. Мда.
