### ISSUE TITLE
Installable Root CA (.cer) now generates automatically on Windows ?

### ISSUE THREAD

**Issue by Baltazar500** [krlvm/PowerTunnel#29]
Немного не понял, что подразумевается под "Installable Root CA (.cer) now generates automatically on Windows" - теперь сертификат будет ставиться автоматом ? А ранее сгенерированные сертификаты будут валидны ?

**Comment by krlvm** [comment]
Теперь не нужно копировать `.pem` файл и переименовывать его в `.cer` для установки, как написано в инструкции, теперь это делается автоматически.
