### ISSUE TITLE
Some websites need to be refreshed several times to get a complete page

### ISSUE THREAD

**Issue by miaomiaosoft** [krlvm/PowerTunnel#3]
I recorded a video demonstration. Some websites may be incomplete when loaded. I need to refresh many times to get a complete website.
I am not Russian, I am in China, but we have a similar firewall.

https://mega.nz/#!4cFFyK5I!kXxtO1NnTu7BryEhSzaJ_oJcJoWit6xHOEKG2Jukn_I

**Comment by krlvm** [comment]
I think this has something to do with redirecting to the stub of your provider. Do you know the address of this page? Try to add it to the `isp-stub.txt`
I will try to disable the option of one-time packet chunking.
I never thought it was so easy to get around the lock in China.

**Comment by krlvm** [comment]
Try this

[PowerTunnel-Experimental.zip](https://github.com/krlvm/PowerTunnel/files/3778590/PowerTunnel-Experimental.zip)

**Comment by krlvm** [comment]
Also I wanted to said that I can add the global mode option but I discovered that it leads to high CPU utilization

**Comment by miaomiaosoft** [comment]
In the government-blacklist file, I used this method to match most domain names, just like the global mode:
com
org
net

It works.

I'll try PowerTunnel-Experimental.zip

**Comment by miaomiaosoft** [comment]
I tried the new procedure, but the problem remained.
I don't know what "isp-stub" means, is it a route exit?  Like this:
![20191028202653](https://user-images.githubusercontent.com/4084875/67678394-747f1280-f9c1-11e9-9024-c102fed0897f.jpg)

**Comment by krlvm** [comment]
When you tries to open a blocked website in Russia, you'll get from your Internet Service Provider redirect to something like this:
![stub](https://user-images.githubusercontent.com/51774833/67678556-ee9aa180-f997-11e9-9a9f-4239b035e722.png)

**Comment by miaomiaosoft** [comment]
No, it will not be redirected in China. The firewall only discards the Server Name Indication (SNI) data of HTTPS websites.

**Comment by krlvm** [comment]
Have you tried low-level utilities like GoodbyeDPI (https://github.com/ValdikSS/GoodbyeDPI)?

**Comment by miaomiaosoft** [comment]
Yes, I have tried goodbydpi, and I found PowerTunnel from the author of goodbydpi, but goodbydpi is only valid for HTTP websites.

**Comment by krlvm** [comment]
It is also support HTTPS, at least in Russia. Can you send HTTPResponse example when site isn't loading from a first attempt? This version dumps it. Better working with Firefox
[PowerTunnel ExperimentalD.zip](https://github.com/krlvm/PowerTunnel/files/3778695/PowerTunnel.ExperimentalD.zip)

**Comment by miaomiaosoft** [comment]
like this?

![20191028210022](https://user-images.githubusercontent.com/4084875/67680593-7e574480-f9c6-11e9-8e45-38b7a3de2731.jpg)

**Comment by krlvm** [comment]
No, in the logs. I updated jar file
![dumph](https://user-images.githubusercontent.com/51774833/67680905-4d164e80-f99d-11e9-9c91-48b78fb43d8b.png)
[PowerTunnel ExperimentalD2.zip](https://github.com/krlvm/PowerTunnel/files/3778775/PowerTunnel.ExperimentalD2.zip)

**Comment by miaomiaosoft** [comment]
[LOG.txt](https://github.com/krlvm/PowerTunnel/files/3778796/LOG.txt)

The logs include：
1. Browse https://cn.reuters.com/ （Success）
2. Browse https://cn.wsj.com/ （Failure）

**Comment by krlvm** [comment]
I tried to visit cn.wsj.com (it isn't blocked in my country) and I got a different response. Actually response comes from the AWS CDN (CloudFront) and contains a redirect. I'll try to add global mode option, I hope it will solve your problem.

Normal response:
`----------------------------
DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 301 Moved Permanently
Server: CloudFront
Date: Mon, 28 Oct 2019 13:30:40 GMT
Content-Type: text/html
Content-Length: 183
Connection: keep-alive
Location: https://cn.wsj.com/
X-Cache: Redirect from cloudfront
Via: 1.1 1405f8b432a21800efb933586c181f09.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: ARN53
X-Amz-Cf-Id: mFEP9yEG9Ba0_4-cr4DRR9L6Nl5cBKftMfaFbRMFgZDtMi5vMN4s9A==
----------------------------`

**Comment by krlvm** [comment]
Please try this, it marks all sites other than the `.cn` domain as blocked.
[PowerTunnel-CNGlobal.zip](https://github.com/krlvm/PowerTunnel/files/3778872/PowerTunnel-CNGlobal.zip)

**Comment by miaomiaosoft** [comment]
I tried PowerTunnel-CNGlobal.zip
And emptied government-blacklist

I opened those two sites again but failed for the first time and started loading data after refreshing

**Comment by krlvm** [comment]
I just released an update, that gives ability to change size of chunk array. Try "play" with it number, defaulting to 1. If it wouldn't help, it is fault of the Amazon Web Services.

java -jar PowerTunnel.jar [CHUNK_SIZE]

**Comment by miaomiaosoft** [comment]
I tried 1-6
But only 1 can work and also needs to be refreshed

Thank you for trying to solve the problem for me. 
Long live freedom！

**Comment by krlvm** [comment]
It’s sad.
I suggest you try to use GoodbyeDPI mode 1 - it works with HTTPS, PowerTunnel uses the same algorithm. Also I can suggest zapret. GreenTunnel doesn't work for me.

**Comment by krlvm** [comment]
Probably fixed in version 1.5, can you check it?

**Comment by miaomiaosoft** [comment]
I tried 1.5

java -jar PowerTunnel.jar ：Unable to open blocked website
java -jar PowerTunnel.jar -chunksize 1-6  ：Unable to open blocked website
java -jar PowerTunnel.jar -full-chunking  ：Unable to open blocked website

It seems that it is not working properly.
I saw an error in the console, I don't know whether it is related to it:
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".

**Comment by miaomiaosoft** [comment]
You don't have China's network environment to test, which may cause some trouble in trying to solve China's blockade.

So I recommend another item recently discovered for your reference，Perhaps it is also applicable to Russian networks：https://github.com/Macronut/TCPioneer

It can be used to open almost all websites that are blocked in China, just like removing the firewall. It is very effective and stable.

**Comment by krlvm** [comment]
> I tried 1.5
> 
> java -jar PowerTunnel.jar ：Unable to open blocked website
> java -jar PowerTunnel.jar -chunksize 1-6 ：Unable to open blocked website
> java -jar PowerTunnel.jar -full-chunking ：Unable to open blocked website
> 
> It seems that it is not working properly.
> I saw an error in the console, I don't know whether it is related to it:
> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".

You should use `-chunk-size` instead of `-chunksize`. This error is dedicated to the LittleProxy logger. In previous versions chunk size was 1 or 2.

TCPPioneer is pretty interesting solution, seems it sends a fake TLS packet like the latest version of GoodbyeDPI.

Thank you, anyway

**Comment by miaomiaosoft** [comment]
Sorry, I forgot you changed the parameter name.
I retested, but it seems to be the same result.
java -jar PowerTunnel.jar -chunk-size 1-6
