### ISSUE TITLE
В билде 1.14 появился дубликат опции "port".

### ISSUE THREAD

**Issue by Baltazar500** [krlvm/PowerTunnel#30]
В билде 1.14 появился дубликат опции "port". Там была другая опция или это просто дубликат ?

**Comment by krlvm** [comment]
О каком порту идёт речь? Upstream proxy - это прокси-сервер, через который прокси-сервер PT подключается к интернету.

**Comment by Baltazar500** [comment]
>О каком порте идёт речь? Upstream proxy - это прокси-сервер, через который прокси-сервер PT подключается к интернету.

да собственно непоятки с аргументами

```
 -ip [IP Address]                        sets IP Address
 -port [Port]                            sets port
 -upstream [ip:port]                     enables upstream proxy and sets its address
 -upstream-auth [user:password]          sets upstream proxy authorization credentials
 -port [Port]                            sets port

```

Если "upstream [ip:port]', то куда ещё один "port" ? Или там только "[ip]" должен быть ?

**Comment by krlvm** [comment]
Дубликат произошел по моей невнимательности, этот параметр задает порт прокси-сервера, как и раньше.
