### ISSUE TITLE
Create automatic startup service

### ISSUE THREAD

**Issue by cantunborn** [krlvm/PowerTunnel#31]
Currently there is no startup service. If program is left running, on restart we need to either start server manually or disable configured proxy for internet to work.

To solve this issue you can create a service which when enabled:
- Runs automatically on startup by default
- Starts proxy server
- Enables proxy in settings

Another improvement would be to create an option to not minimize on close. For permanent setup, service will be registered in Windows 10 which will be more convenient.

**Comment by krlvm** [comment]
It is problematic to allow to run the program as a Windows service since it is written in Java, but you can put this batch script in your autorun folder:

```bat
@ECHO OFF
start javaw -jar PowerTunnel.jar -console
```
