### ISSUE TITLE
Tunnel connection failed multiple sites

### ISSUE THREAD

**Issue by cantunborn** [krlvm/PowerTunnel#32]
Not working for me anymore. For multiple sites which are confirmed to be censored, chrome shows `ERR_TUNNEL_CONNECTION_FAILED` on default powertunnel settings.

**Comment by krlvm** [comment]
Most likely your ISP has started to use more efficient DPI system, I can only suggest that you try changing chunk/fragment size or enable SNI tricks - but they could break some non-blocked websites, so you should fill the `government-blacklist.txt` for selective use.
