### ISSUE TITLE
Installing SNI Root CA on Linux

### ISSUE THREAD

**Issue by NoUserNameForYou** [krlvm/PowerTunnel#33]
1.  Move the cert to proper location
2. Copy the certificate `pem` to `/etc/pki/ca-trust/source/anchors`
3. Execute: `cp mycert.pem /etc/pki/ca-trust/source/anchors/mycert.pem`
4. Update trusted certificates
5. After moving the cert to `/etc/pki/ca-trust/source/anchors/`, then `run update-ca-trust`

This will reload all of the trusted certificates, including the one you added.

**Comment by krlvm** [comment]
Thank you for useful information
