### ISSUE TITLE
OpenWRT Support Please

### ISSUE THREAD

**Issue by amanjuman** [krlvm/PowerTunnel#35]
It would really Awsome if we can use PowerTunnel with  OpenWRT since this will allow the whole network to bypass DPI. This way many smart home device like Smart TV etc will able to access DPI blocked sites. An OpenWRT Web Version App would be really nice.

**Comment by krlvm** [comment]
You can use PowerTunnel on OpenWRT if you can install Java on it.
If you can't, you can use [zapret](https://github.com/bol-van/zapret).

**Comment by sajati** [comment]
hi @krlvm i installed java on openwrt following this tutorial https://dev.to/reinhart1010/apparently-yes-you-can-install-openjdk-java-jre-and-yacy-on-openwrt-1e33 and tried to run powertunnel, looks like it succeeded (no error notes on screen), what to do next ?
![image](https://user-images.githubusercontent.com/40118498/180625495-4ccab9a8-60bd-41ee-b530-71f0c7ec3ec3.png)

**Comment by krlvm** [comment]
You need to make OpenWRT to redirect all traffic to the proxy server.
I think it is more performant to use [zapret](https://github.com/bol-van/zapret) in this case

**Comment by sajati** [comment]
fyi: im using openwrt on arm quadcore s905 tv box, with 2gb ram and 32gb sdcard, so maybe performance isn't a big problem, i need to know how to do that `redirect all traffic to the proxy server.`, also i have https-dns-proxy installed on openwrt, will it cause issues with powertunnel ?

**Comment by sajati** [comment]
i tried to set proxy on ms-windows (192.168.68.1 is openwrt IP), but it says not connected 
![image](https://user-images.githubusercontent.com/40118498/180625711-bd68eeb3-a723-4f06-b849-67b47ecf090d.png)

**Comment by krlvm** [comment]
Set PowerTunnel address to 0.0.0.0 and use `192.168.1.1:8085`
