### ISSUE TITLE
Start without main window (minimized to tray)

### ISSUE THREAD

**Issue by YellowSM** [krlvm/PowerTunnel#36]
Можно добавить ключ запуска, чтобы PowerTunnel запускался сразу свернутым в трэй?

**Comment by krlvm** [comment]
Если это нужно для автоматического запуска, то лучше запускать в консольном режиме через `javaw` для скрытия окна терминала, настройки будут считаны из рабочей директории:
`start javaw -jar PowerTunnel.jar -console`

**Comment by YellowSM** [comment]
> Если это нужно для автоматического запуска, то лучше запускать в консольном режиме

Про консольный режим я знаю. Я предлагаю добавить ключ запуска (например, -minimized), при использовании которого при запуске главное окно не появляется, но в трее приложение отображается. Т.е. чтобы можно было управлять приложением через трей, но главное окно бы скрывалось при запуске.

**Comment by krlvm** [comment]
Для запуска с выводом в терминал:
`java -jar PowerTunnel.jar -minimized -start`

Для запуска в тихом режиме:
`start javaw -jar PowerTunnel.jar -minimized -start`

[PowerTunnel.zip](https://github.com/krlvm/PowerTunnel/files/6486837/PowerTunnel.zip)

**Comment by YellowSM** [comment]
Спасибо! То, что надо.
