### ISSUE TITLE
It does not work.

### ISSUE THREAD

**Issue by toprak** [krlvm/PowerTunnel#37]
Hi, I've been using its mobile version since 4~ months and it works flawlessly, but I can not make it work on Linux desktop even though I am using the same settings that I use on phone.

**Comment by krlvm** [comment]
Are you sure you're configured proxy server correctly?
Also, some software (antiviruses, firewalls, etc.) that inspect your traffic to identify threats can correct your traffic modified by PowerTunnel during the inspection, for example, merge fragmented packets, etc.

**Comment by toprak** [comment]
I did everything same as phone's, there are nothing that blocks powertunnel I guess, I'm not advanced linux user

**Comment by krlvm** [comment]
Unlike Android, you need to manually configure the proxy server on your PC: PowerTunnel configures it automatically on Windows, but on Linux/macOS you need to configure it yourself: either set it as system-wide proxy server, either you can try configuring it for Firefox only for example: https://support.mozilla.org/en-US/kb/connection-settings-firefox (also enable `Also use this proxy for FTP and HTTPS` option).
The default IP is `127.0.0.1` and the default port is `8085`.

**Comment by toprak** [comment]
Yey it worked!
