### ISSUE TITLE
DNS resolving timeout

### ISSUE THREAD

**Issue by toprak** [krlvm/PowerTunnel#38]
I am using Chromium on Linux, so I set proxy system-wide, it PowerTunnel works good but whenever I am afk I have to reset proxy server, if I dont it wont work.

**Comment by krlvm** [comment]
Check app logs, you can temporary enable logging in options.

**Comment by toprak** [comment]
@krlvm here, [terminal output](https://pastebin.com/qd08rKqj) [log](https://pastebin.com/Wx06DMpV) I dunno what to do.

**Comment by krlvm** [comment]
This is a problem with DNS resolving, do you have DNS override (custom DNS provider) enabled ?

**Comment by toprak** [comment]
@krlvm Yes, 8.8.8.8 that written in read me

**Comment by toprak** [comment]
I changed it to cloudflare still same issue, but I have to use DOH too.

**Comment by krlvm** [comment]
You may try disabling DNS settings in PowerTunnel and enabling it only in Chrome (`chrome://settings/security`) to see does it help you.

**Comment by toprak** [comment]
@krlvm it is not available on linux sadly.

**Comment by krlvm** [comment]
Most likely it is related to the [bug](https://github.com/dnsjava/dnsjava/pull/96) in dnsjava, it should be [fixed](https://github.com/dnsjava/dnsjava/pull/177) now, but unfortunately they have not released a new version. I've never experienced this on Windows though.
You can either disable this functionality at the moment, either try `https://8.8.8.8/dns-query`.

**Comment by toprak** [comment]
@krlvm I was using "https://8.8.8.8/dns-query" already, guess have to wait right?

**Comment by krlvm** [comment]
Unfortunately, we can only wait for the dnsjava update with the patch, or this is some kind of problem not related to it.

**Comment by krlvm** [comment]
A new version of dnsjava has released with a fix, try this build: 
[PowerTunnel-dns.zip](https://github.com/krlvm/PowerTunnel/files/6626808/PowerTunnel-dns.zip)

**Comment by toprak** [comment]
@krlvm I am using Linux, it is working cool on android.

**Comment by krlvm** [comment]
Oh, didn't notice
[PowerTunnel-dns-pc.zip](https://github.com/krlvm/PowerTunnel/files/6626839/PowerTunnel-dns-pc.zip)

**Comment by toprak** [comment]
it worked yey, thanks!

**Comment by toprak** [comment]
it is same...
