### ISSUE TITLE
"Broken" symbols in console when log file enabled

### ISSUE THREAD

**Issue by YellowSM** [krlvm/PowerTunnel#40]
Так, мелочь: при запуске с параметрами `-console -enable-log-to-file` в консоли появляются "битые" символы:

![console-n-log](https://user-images.githubusercontent.com/5058386/123559919-bd472a00-d7a7-11eb-9434-beb4cf3a1aff.png)

Без лога всё нормально. Винда 10-ка, русская, PowerTunnel 1.14

**Comment by krlvm** [comment]
Это проблема с кодировкой командной строки. Попробуйте запускать с параметром Java:
`java -Dfile.encoding=UTF-8 -jar ...`

**Comment by YellowSM** [comment]
Да, помогло. Спасибо!
