### ISSUE TITLE
CLI option?

### ISSUE THREAD

**Issue by mrbluecoat** [krlvm/PowerTunnel#42]
I'm hoping to run on Linux headless. Does the jar support CLI mode?

**Comment by mrbluecoat** [comment]
Never mind, looks like LibertyTunnel is intended for that mode. https://github.com/krlvm/PowerTunnel/tree/libertytunnel

**Comment by krlvm** [comment]
Don't use LibertyTunnel, it hasn't been updated since March 2020, use PowerTunnel with `-console` flag instead, it does the same:
`java -jar -PowerTunnel.jar -console`
