### ISSUE TITLE
Docker instructions

### ISSUE THREAD

**Issue by ackr-8** [krlvm/PowerTunnel#43]
Hello there, I have created a docker container for PowerTunnel so that people can deploy it onto their NAS/Home server so that whole network can get PowerTunnel proxy. I would suggest adding a link to docker hub so it would be easy for anyone to deploy.
Links:
[Docker Hub](https://hub.docker.com/r/ackr8/powertunnel)
[Source](https://github.com/ackr-8/powertunnel-dockerized)

**Comment by krlvm** [comment]
Hello, thanks for the contribution, I added the link to the [Installation manual](https://github.com/krlvm/PowerTunnel/wiki/Installation#getting-the-executable).

I'd also replace this [line](https://github.com/ackr-8/powertunnel-dockerized/blob/a1dce01a7e2b2363d28778de87da1cc3f4bdcc0d/Dockerfile#L7) with `RUN wget https://github.com/krlvm/PowerTunnel/releases/latest/download/PowerTunnel.jar`, so it always will ship the latest PowerTunnel version.

**Comment by ackr-8** [comment]
No this is not a fork as my docker container runs on all the major platforms, his image wouldn't run on arm and arm64 devices so raspberry pi and other NASs won't be able to run the docker container. I have a different base compared to his which is smaller and faster. I didn't include the latest coz docker downloads the .jar when I'm building the container and not when a user downloads my container and it also gives me an opportunity to thoroughly test the container before a user downloads it.

**Comment by krlvm** [comment]
Ok, thanks!

**Comment by ackr-8** [comment]
Also it seems his docker container is not maintained, its still on v1.13.
