### ISSUE TITLE
Встроенный апдейтер PT ломится через прокси прописанный в IE

### ISSUE THREAD

**Issue by Baltazar500** [krlvm/PowerTunnel#58]
Собственно сабж. 

А т.к. у меня там фейк - заглушка с несуществующим прокси, я получаю вот такую ошибку :

>23:54:24.053 [Main App Update Checking Thread] WARN  io.github.krlvm.powertunnel.desktop.updater.UpdateNotifier - Failed to check for updates: https://raw.githubusercontent.com/krlvm/PowerTunnel/tree/next/master/VERSION

ну и огромный выхлоп jav'ы в довесок

**Comment by krlvm** [comment]
Проблема в том, что пока я не объединил ветки данный адрес для проверки обновлений недоступен (404), отсюда и ошибка.
В следующей версии будет добавлен интервал проверки обновлений в 24 часа.
