### ISSUE TITLE
Support for IPv6

### ISSUE THREAD

**Issue by ackr-8** [krlvm/PowerTunnel#59]
Is it possible to add IPv6 support to powertunnel, as the web is moving towards it and IPv4 addresses are already reaching their limit afaik goodbyedpi doesn't support ipv6.

**Comment by krlvm** [comment]
Doesn't it has IPv6 support already?
https://ipv6test.google.com/

**Comment by ackr-8** [comment]
I get 0/10 error with firefox as well as chromium with proxyswitchyomega. Is it even possible as when we enter proxy details we only enter 127.x.x.x so thats only an IPv4 address.

**Comment by ackr-8** [comment]
This issue is actually an issue with docker's NAT and its soon going to be overhauled. Hence I'm closing this issue.
P.S. I am releasing the 2.0 RC-4 in preview channel on docker hub and will report any issues here.

**Comment by krlvm** [comment]
Thanks for confirming!
