### ISSUE TITLE
Provide a better documentation

### ISSUE THREAD

**Issue by tommirp** [krlvm/PowerTunnel#6]
Hello, i try to follow the setup instructions but it doesnt work in my laptop. I dont really understand about the step. Maybe u can make a tutorial vid or step by step with screenshoot image? This is awesome! Thanks for the power tunnel idea. It really works in android phone. But i start to implement it to my laptop and android tv too, it still doesnt work. 👍

**Comment by krlvm** [comment]
Sorry, I'm not a native English speaker

1) Install Java (you can download Java [here](https://www.java.com/en/download/win10.jsp)
2) Download PowerTunnel and move the file to a new folder
3) Create file `government-blacklist.txt`. If you know a site that provides your country's government blocklist, copy it. If you don't, put an asterisk (`*`) there, i.e.:
![universalblocklist](https://user-images.githubusercontent.com/51774833/80519053-0c20e600-8990-11ea-9fe6-d19cb303c2cb.png)
[Download universal blocklist](https://github.com/krlvm/PowerTunnel/files/4547507/government-blacklist.txt)
4) Launch PowerTunnel.jar and click `Start server`
5) If you're using Windows, proxy server should've been setup automatically. If it wasn't, follow [this instruction](https://www.howtogeek.com/tips/how-to-set-your-proxy-settings-in-windows-8.1/). Proxy IP and port is visible in the PowerTunnel window, i.e.:
![powertunnel-proxy](https://user-images.githubusercontent.com/51774833/80519520-c87aac00-8990-11ea-80c0-05fe5baa4f15.png).
If you're using a Linux distribution/macOS, google instruction for it.
6) PowerTunnel should work. You can check if it does by opening logs - if it works, messages will constantly come there.

If you close PowerTunnel window when it runs, it will not stop, it will be hidden in tray. Proxy server automatically disables on Windows after you've stopped PowerTunnel, if it did not, just open and close Internet Explorer.

If you want to start PowerTunnel with Windows start, create batch file with command
`javaw -jar PATH\TO\POWERTUNNEL.jar -console` and put it to the autorun folder.

Tell if you have any questions.

**Comment by hoducha** [comment]
Awesome, it works for me on my Macbook. I think some people expect it works out of the box after starting the program so we might consider updating the Installation page in order to: 
- Highlight the configuring the Network Web Proxy step by adding some images.
- Put an asterisk (*) as the default values for `government-blacklist.txt`, and add an instruction on how to block only specific sites.

**Comment by krlvm** [comment]
> Awesome, it works for me on my Macbook. I think some people expect it works out of the box after starting the program so we might consider updating the Installation page in order to:
> 
> * Highlight the configuring the Network Web Proxy step by adding some images.
> * Put an asterisk (*) as the default values for `government-blacklist.txt`, and add an instruction on how to block only specific sites.

I think the best way is setting default `government-blacklist.txt` value to an asterisk or adding a global mode option. I'll try make an update during the day.

**Comment by krlvm** [comment]
I've released [v1.10.1](https://github.com/krlvm/PowerTunnel/releases/tag/v1.10.1) with global mode (asterisk in blocklist) enabled by default.
Thanks for your feedback.

**Comment by krlvm** [comment]
Instructions on PowerTunnel [Wiki](https://github.com/krlvm/PowerTunnel/wiki/Installation) has been updated

**Comment by tommirp** [comment]
You are so great! Hope this can help many people in goodness. I will continue testing and give input if you allow me. Thank you very much!

**Comment by Crypto-Spartan** [comment]
I'm curious as to how PowerTunnel actually works from a network standpoint. What exactly does it do to the traffic to circumvent internet censorship and DPI? I feel like this would also be a good topic for any documentation added.

**Comment by krlvm** [comment]
> I'm curious as to how PowerTunnel actually works from a network standpoint. What exactly does it do to the traffic to circumvent internet censorship and DPI? I feel like this would also be a good topic for any documentation added.

I do not think I can write a clearly readable documentation on my own, but you may want to read a [short overview of how GoodbyeDPI works](https://github.com/ValdikSS/GoodbyeDPI#how-does-it-work), since PowerTunnel is just yet another implementation of it, the only difference is that PowerTunnel is aimed on cross-platform support and written in 100% Java.

**Comment by krlvm** [comment]
If you are sure your traffic goes through the proxy and you still can't access blocked websites you can try using SNI Tricks bypass method. If it doesn't work your ISP blocks the resource you need by IP address and the restriction can only be bypassed using Encrypted VPN/Proxy or Tor.

**Comment by parmetra** [comment]
The thing is, I'm not really sure if the traffic is going through the proxy server. Of course, I did it according to the instructions. But I don't know if I did it that way. When I open the logs, this is what I see:
```
PowerTunnel version 1.14
Simple, scalable, cross-platform and effective solution against government censorship
https://github.com/krlvm/PowerTunnel
(c) krlvm, 2019-2021

[Updater] You're running the latest version of PowerTunnel!
[i] Loaded '1' government blocked sites, '0' user blocked sites, '0' user whitelisted sites

[.] Starting LittleProxy server on 127.0.0.1:8085
[.] Server started

[*] System proxy setup has finished
```


But I am sure that the provider can be bypassed, because everything works through the GoodbyeDPI program. However, I still use DNS there to make everything work out

**Comment by krlvm** [comment]
PowerTunnel doesn't support GoodByeDPI's `--set-ttl` and `--wrong-chksum`, if you don't use these flags, [try to set proxy server manually](https://www.howtogeek.com/tips/how-to-set-your-proxy-settings-in-windows-8.1/), or try [the Android version](https://github.com/krlvm/PowerTunnel-Android) - it works in VPN mode so guaranteed proxies all your traffic and you can determine whether PT compatible with your ISP.

**Comment by krlvm** [comment]
I wrote the most detailed guide [here](https://github.com/krlvm/PowerTunnel/wiki/Installation), tell me what I can add more if you have any questions.
