### ISSUE TITLE
It stopped working

### ISSUE THREAD

**Issue by Gekyyyy** [krlvm/PowerTunnel#60]
I might have messed with some settings that made it just not work on any network.
I reset the powertunnel settings made sure Java is up to date and everything so its probably my computer but I'm not sure how to fix it.
The proxy server is inresponsive when I ping it with cmd `ping 127.0.0.1:8085` I don't know if thats normal.
For the first time it was able to to bypass DPI easily and there was nothing wrong with it what so ever but now its just not working.
I tried 2 other DPI blockers and they also seem to not work.

If you have any clue as to what happened it would be very cool if you help out,  thx.

**PS. I tested it on internet explorer its working fine, but chrome doesnt.**

**Comment by krlvm** [comment]
Sorry for late response, for some reason I did not receive the notification.
Which version of PowerTunnel you use?

PowerTunnel is a proxy server, that means all your traffic should be redirected to it to take the desired effect.
This can be done in two ways: via setting system global proxy server and via setting proxy server per browser.
On Windows, PowerTunnel configures system proxy server automatically, but you could've disabled it - check your options:
![image](https://user-images.githubusercontent.com/51774833/135711436-71352475-df39-4d76-a731-7933afb5a5d6.png)
You can also try to configure it manually: https://www.howtogeek.com/tips/how-to-set-your-proxy-settings-in-windows-8.1/

If PowerTunnel has effect in Internet Explorer, but does not in Chrome, that means that Chrome traffic is not proxied.
I think your Chrome shortcut has option `--no-proxy-server` (or option which sets the proxy server) or you have some proxy or VPN extension installed - it may change proxy server dynamically. A new extension menu was introduced in the recent Chrome versions, so you may not see all your installed extensions on toolbar - check `chrome://extensions/` page.

If you have Firefox installed, you can also try configuring proxy server separately for Firefox (don't forget to check "Use this proxy for FTP and HTTPS"):
![image](https://user-images.githubusercontent.com/51774833/135711604-83241f27-cd0d-4cde-9aec-d06f8dba7389.png)
