### ISSUE TITLE
DNS Resolver plugin isn't working

### ISSUE THREAD

**Issue by androidghosh** [krlvm/PowerTunnel#66]
When I disable "allow ignoring DNS server on failure", no matter what settings of DNS I use not a single site works, chrome returns with "This page isn’t working".

When I enable "allow ignoring DNS server on failure", no matter what DNS settings I chose, this application uses my default ISP DNS. 

tl;dr  this application either uses my default ISP DNS or it fails to resolve any [domain](https://i.ibb.co/9NBC2qq/Screenshot-2021-09-30-132219.jpg)

**Comment by krlvm** [comment]
Which PowerTunnel version you are using?
When custom DNS resolver fails to resolve a domain, the application prints the error cause to the log, can you check it?
