### ISSUE TITLE
Не работает обход блокировки http-протокола.

### ISSUE THREAD

**Issue by Baltazar500** [krlvm/PowerTunnel#8]
С английским у меня туговато, так что лучше я буду на русском писать. 

Решил потестить PowerTunnel под win, раз тулза под андроидом оказалась вполне работоспособным способом обхода, но почему-то по http до рутрекера достучаться не удалось, как не игрался с настройками и не перезапускал сервер. По https сайт без проблем открывается, а по http в консоль сыпется вот такое :

>[i] GET / rutracker.org
> [+] Trying to bypass DPI: rutracker.org
>1375797 [LittleProxy-4-ProxyToServerWorker-0] INFO org.littleshoot.proxy.impl.ProxyToServerConnection - (AWAITING_INITIAL) [id: 0xc3bac531, L:/192.168.1.230:20841 - R:rutracker.org/195.82.146.214:80]: An IOException occurred on org.littleshoot.proxy.impl.ProxyToServerConnection: Удаленный хост принудительно разорвал существующее подключение
>1375803 [LittleProxy-4-ProxyToServerWorker-0] INFO org.littleshoot.proxy.impl.ProxyToServerConnection - (AWAITING_INITIAL) [id: 0xc3bac531, L:/192.168.1.230:20841 - R:rutracker.org/195.82.146.214:80]: Disconnecting open connection to server
>1389639 [LittleProxy-4-ClientToProxyWorker-0] INFO org.littleshoot.proxy.impl.ClientToProxyConnection - (AWAITING_INITIAL) [id: 0xb6cc1cba, L:/127.0.0.1:8085 - R:/127.0.0.1:20840]: An IOException occurred on ClientToProxyConnection: Удаленный хост принудительно разорвал существующее подключение

с PowerTunnel  под Android проблем с обходом блокировки http на том же провайдере и втой же сети не было.

**Comment by krlvm** [comment]
Android-версия PowerTunnel использует тот же самый "надстроенный" LittleProxy-сервер (тот же самый код), вы пишете, что Android-версия помогает обойти блокировку, значит, проблема не в самом PowerTunnel.

Почему так могло получиться?
1. Android-версия работает не по спискам заблокированных сайтов, а в "глобальном" режиме - это звездочка (`*`) в `government-blocklist.txt`. Она там находится по умолчанию с версии 1.10.1. Вы же, возможно, используете список заблокированных сайтов.
2. Возможно проблема с DNS (хотя, мне так не кажется - в вашем логе указан корректный адрес rutracker). Если вы используете стороннего поставщика DNS на мобильном PowerTunnel, укажите его и в настольной версии, если нет - отключите.
3. Если у вас отключен "глобальный" режим - вы используете свой собственный список для обхода блокировок, добавьте туда `rutrk.org` - к нему также обращается rutracker при подключении. Я рекомендую для России автообновляемый список из GoodbyeDPI, расположенный по адресу https://antizapret.prostovpn.org/domains-export.txt - вы можете скопировать его содержимое в `government-blacklist.txt`, либо указать его в ключе `-government-blacklist-from https://antizapret.prostovpn.org/domains-export.txt`, или здесь, предварительно очистив `government-blacklist.txt` (я, кстати, использую вот такую конфигурацию):
![gov-mirror](https://user-images.githubusercontent.com/51774833/81442698-c2e54900-917c-11ea-8a25-81dc07286c84.png)
 
Предположу, что что-то мешает Java "достучаться" до сервера, возможно, брандмауэр, но это было бы странно, поскольку все остальное успешно открывается.
Проблема здесь не в обходе блокировки: эта ошибка указывает на проблемы соединения с ресурсом: ресурс разрывает соединение. Если сайт заблокирован, то соединение не разрывается, приходит либо редирект на заглушку провайдера, либо клиент ловит таймаут.

Посмотрите в сторону остального ПО, работающего на вашем ПК (может, вы использовали другие средства обхода блокировок, или какие-нибудь программы для отслеживания сетевой активности из сетевого стека операционной системы) возможно, что проблема в нем. Если у вас есть сомнения:

1. Попробуйте подключиться по http к любому другому заблокированному сайту, например, DailyMotion, заблокированный в России, работает только по HTTPS, но при подключении по обычному HTTP приходит редирект на HTTPS-адрес. Если обход блокировки не работает, вы получите редирект на заглушку провайдера, если работает - редирект на HTTPS-адрес DailyMotion. http://dailymotion.com
2. Попробуйте запустить PowerTunnel на виртуальной машине, хотя, это, скорее всего, не даст никакого эффекта, поскольку трафик все равно будет проходить через вашу хостовую ОС.
3. Попробуйте запустить настольную версию PowerTunnel на другом устройстве, подключенным к вашей сети, или на другой операционной системе на вашем устройстве (Dual-Boot конфигурация, если есть, или LiveCD Linux-дистрибутива)

![rutracker](https://user-images.githubusercontent.com/51774833/81439615-5156cc00-9177-11ea-92ed-d04386e1177f.png)

**Comment by Baltazar500** [comment]
Пхоже это какая-то конкретная придурь рутрекера. Я для ускорения тестирования проводил тесты через curl и xidel, который парсит заголовок страницы и без браузерного юзерагента рутрекер даёт отлуп запросам.

Во время тестов выяснилась ещё одна придурь - при прохождении через прокси несжатого запроса 

>curl -x 127.0.0.1:8085 -sLk -H "User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:52.0) Gecko/20100101 Firefox/52.0" "http://rutracker.org"

рутрекер отдаёт

>HNGJpP5b-452

при этом если послать сжатый запрос

>curl --compressed -x 127.0.0.1:8085 -sLk -H "User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:52.0) Gecko/20100101 Firefox/52.0" "http://rutracker.org"

то рутрекер нормально отдаёт страницу.

При этом, если запрос не имеет сжатия и проходит напрямую, минуя прокси (с изменённым хедером хоста)

>curl -sLk -H "hOST: rutracker.org" -H "User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:52.0) Gecko/20100101 Firefox/52.0" "http://rutracker.org"

то рутрекер отдаёт страничку.

В общем, плохой я сайт выбрал для тестов. В браузере он без проблем открылся. Если хотите, можете что-то допилить в этом направлении, открыв отдельное issue, но конкретно данный вопрос закрыт.

**Comment by krlvm** [comment]
Похоже на обычную защиту от ботов.

**Comment by krlvm** [comment]
> При этом, если запрос не имеет сжатия и проходит напрямую, минуя прокси (с изменённым хедером хоста)

PowerTunnel еще и добавляет точку после адреса, таким образом получается "hOST: rutracker.org."
