### ISSUE TITLE
Встроенный лог содержит лишь stdout ?

### ISSUE THREAD

**Issue by Baltazar500** [krlvm/PowerTunnel#9]
Обратил внимание, что в консоль сыпется куда больше полезной информации, которой нет во встроенном логе. А это оказывается stderr. А в лог отправляется лишь stdout, который в консоли тоже есть. Мб стоит stderr во встроенном логе тоже писать ?

**Comment by krlvm** [comment]
Это родной логгер LittleProxy, который используется как базовый прокси-сервер.
Я разработал прослойку для зеркалирования этих сообщений, и вообще всего stdout/stderr во встроенный лог, но похоже на то, что он негативно влияет на производительность приложения (это не точно) и некоторые другие вещи.
Для этого нужно установить значение [этой](https://github.com/krlvm/PowerTunnel/blob/master/src/ru/krlvm/powertunnel/PowerTunnel.java#L69) переменной на `true`, что можно сделать, запустив PowerTunnel с ключом `-full-output-mirroring`.

Встроенный лог же реализуется вот [здесь](https://github.com/krlvm/PowerTunnel/blob/master/src/ru/krlvm/powertunnel/utilities/Utility.java#L33) и печатается напрямую в окно с дублированием в stdout.

Похоже, что LittleProxy уже около трех лет заброшен мейнтернерами, поэтому я рассматриваю варианты миграции на другие прокси-серверы. В этих логах нет ничего интересного, они могут полезны разве что для отладки каких-то тонких вещей вроде разрешения DNS.

Также, во встроенный лог могут печататься сообщения о некритичных ошибках (без стектрейса), для этого запустите PowerTunnel с ключом `-debug`.
