### ISSUE TITLE
Использование cfg - параметров из консоли не приносит ожидаемого эффекта.

### ISSUE THREAD

**Issue by Baltazar500** [krlvm/PowerTunnel#97]
Использование cfg - параметров из консоли не приносит ожидаемого эффекта. По UI, который я не отключал, при заходе в настройки плагинов видно, что опции применяются (по дефолту я там снял галки, что отражено и в ini), но эффекта они не дают. Обход не срабатывает. 

Если просто запускаю PT и вручную проставляю через UI данные опции, то эффект есть и обход работает.

Речь о таких параметрах в частности

```

-cfg libertytunnel.modify_sni true -cfg libertytunnel.sni_trick fake -cfg libertytunnel.fake_sni w3.org

```

PT последний, 2.2.1

**Comment by krlvm** [comment]
Сломал совершенно [случайно](https://github.com/krlvm/PowerTunnel/commit/715e798066b3dade1b07e8b7009a1578ea860d9d), версия с исправлением:
[desktop-2.2.1-all.zip](https://github.com/krlvm/PowerTunnel/files/8548696/desktop-2.2.1-all.zip)
