### ISSUE TITLE
About RSS feeds

### ISSUE THREAD

**Issue by darkrising9** [krlvm/PowerTunnel#98]
I stumbled upon this when I wanted to bypass one of the torrent sites (nyaa(dot)si) and also use its RSS feeds, which are both blocked here. I tried using a VPN, it helped open the site but my connection speed dropped drastically, so I started looking for circumvention tools, I installed GoodByeDPI, it worked for a solid 3-4 months but recently stopped working. So, I searched for some alternatives and this was one of the most recommended ones, I installed it, configured it and it helped open the site but the RSS feed won't load, is there some way around that?

**Comment by krlvm** [comment]
RSS does not use a special protocol, it is just a XML document served via HTTP.
If you are able to access the blocked site, you should be able to access the RSS feed if it is located on the same domain.
Make sure the browser or application you are using to read RSS uses PowerTunnel proxy.

**Comment by darkrising9** [comment]
I see, thanks for the response, I'll try that!
