### ISSUE TITLE
government-blacklist.txt not updated

### ISSUE THREAD

**Issue by koinsj** [krlvm/PowerTunnel#99]
I filled out the blacklist url in the LibertyTunnel settings and set it to update on start, but the government-blacklist.txt it generated was blank.

The url I put in:
https://cdn.jsdelivr.net/gh/hezhijie0327/GFWList2AGH@main/gfwlist2domain/blacklist_full.txt

**Comment by koinsj** [comment]
Thanks for your respond!

Sorry if I didn't express the problem precisely. There was no government-blacklist-cache.txt when I set the blacklist to update on start at the very beginning. This file only appeared when I set it to update after a specific time period.

Is it a bug or that's how it works?

**Comment by krlvm** [comment]
Yes, that's why it called cache. 
Also, PowerTunnel loads government-blacklist.txt too, in addition to the hosts which are loaded from the URL.

**Comment by koinsj** [comment]
I get it now. I mistakenly thought that only domains within the blacklist file would affect the filter. Thanks again for the explanation!
